config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    root "base#index"
    resources :users do 
      resources :permissions

      put "permissions", to: "permissions#set", as: "set_permissions"
    end
  end

  root 'projects#index'

  resources :projects do
    resources :tickets
  end

  resources :tickets do
    resources :comments
  end

  resources :users
  resources :files

  get '/signin', to: "sessions#new"
  post '/signin', to: "sessions#create"
  delete '/signout', to: "sessions#destroy", as: "signout"

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :permissions

  scope :admins, ->{ where(:admin => true) }

  def to_s
    "#{email} (#{admin? ? "Admin" : "User"})"
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  def index
    @users = User.order(:email)
  end

  def new
    @user = User.new
  end

  def create
    params = user_params.dup
    params[:password_confirmation] = params[:password]
    @user = User.new(params)

    if @user.save
      redirect_to admin_users_path, notice: "User has been created."
    else
      flash.now[:notice] = "User has not been created."
    end
  end

  def show
  end

  def update
    if params[:user][:password].blank?
      params[:user].delete(:password)
      params[:user].delete(:password_confirmation)
    end

    if @user.update(user_params)
      redirect_to admin_users_path, notice: "User has been updated."
    else
      flash[:notice] = "User has not been updated."
      render action: "edit"
    end
  end

  def edit
  end

  def destroy
    if @user == current_user
      flash[:notice] = "You cannot delete yourself!"
    else
      @user.destroy
      flash[:notice] = "User has been deleted."
    end
    redirect_to admin_users_path
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :admin)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user, except: [:new, :create]

  def new
    @user = User.new
  end

  def show
  end

  def create
    @user = User.create(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to projects_path, notice: "You've signed up successfully."
    else
      render :new
    end
  end
  
  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to @user, notice: "Profile has been updated."
    else
      render :edit
    end
  end


  private

  def find_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation )
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div id="error">
      <h4><%= pluralize(@user.errors.count, "error") %>
        prohibited this project from being saved:</h4>
      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <p>
  	<%= f.label :name, "Username" %><br />
  	<%= f.text_field :name %>
  </p>

  <p>
  	<%= f.label :email %><br />
  	<%= f.email_field :email %>
  </p>
  <p>
  	<%= f.label :password %><br />
  	<%= f.password_field :password %>
  </p>
  <p>
  	<%= f.label :password_confirmation %><br />
  	<%= f.password_field :password_confirmation %>
  </p>


  <% if @user.new_record? %>
    <%= f.submit "Sign up" %>
  <% else %>
    <%= f.submit "Update Profile" %>
  <% end %>

<% end %>

app/views/users/edit.html.erb
<h4>Edit user</h4>
<%= render 'form' %>

app/views/users/new.html.erb
<h4>Sign Up</h4>

<%= render "form" %>

app/views/users/show.html.erb
<h4>User Profile: <%= @user.name %></h4>

<h5><%= @user.name %> Email: <%= @user.email %></h5>

<%= link_to "Edit Profile", edit_user_path(@user) %>