config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    root "base#index"
    resources :users do 
      resources :permissions

      put "permissions", to: "permissions#set", as: "set_permissions"
    end
  end

  root 'projects#index'

  resources :projects do
    resources :tickets
  end

  resources :tickets do
    resources :comments
  end

  resources :users
  resources :files

  get '/signin', to: "sessions#new"
  post '/signin', to: "sessions#create"
  delete '/signout', to: "sessions#destroy", as: "signout"

end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  belongs_to :project
  belongs_to :user
  has_many :assets
  has_many :comments
  validates :title, :description, presence: true
  accepts_nested_attributes_for :assets
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :find_project
  before_action :require_signin!
  before_action :find_ticket, only: [:show, :edit, :update, :destroy]
  before_filter :authorize_create!, only: [:new, :create]
  before_action :authorize_update!, only: [:edit, :update]
  rescue_from ActiveRecord::RecordNotFound, with: :handle_error

  def new
    @ticket = @project.tickets.build
    @ticket.assets.build
  end

  def create
    @ticket = @project.tickets.build(ticket_params)
    @ticket.user = current_user
    if @ticket.save
      flash[:notice] = "Ticket has been created."
      redirect_to [@project, @ticket]
    else
      flash[:notice] = "Ticket has not been created."
      render :action => 'new'
    end
  end

  def edit
  end

  def update
    if @ticket.update(ticket_params)
      flash[:notice] = "Ticket has been updated."
      redirect_to [@project, @ticket]
    else
      flash[:notice] = "Ticket has not been updated."
      render action: "edit"
    end
  end

  def show
    @comment = @ticket.comments.build
  end

  def destroy
    @ticket.destroy
    flash[:notice] = "Ticket has been deleted."
    redirect_to @project
  end

  private
  def authorize_update!
    if !current_user.admin? && cannot?("edit tickets".to_sym, @project)
      redirect_to @project, notice: "You cannot edit tickets on this project."
    end
  end
  def handle_error
    flash[:notice] = "The project you were looking for could not be found."
    redirect_to root_path
  end

  def ticket_params
    params.require(:ticket).permit(:title, :description, assets_attributes: [:asset])
  end

  def find_ticket
    @ticket = @project.tickets.find(params[:id])
  end

  def find_project
    @project = Project.for(current_user).find(params[:project_id])
  end

  def authorize_create!
    if !current_user.admin? && cannot?("create tickets".to_sym, @project)
      flash[:notice] = "You cannot create tickets on this project."
      redirect_to @project
    end
  end
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/tickets/_form.html.erb
<%= form_for [@project, @ticket], html: { multipart: true } do |f| %>
  <% if @ticket.errors.any? %>
    <div id="error">
      <h4><%= pluralize(@ticket.errors.count, "error") %>
        prohibited this project from being saved:</h4>
      <ul>
      <% @ticket.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <p>
  	<%= f.label :title %><br />
  	<%= f.text_field :title %>
  </p>


  <p>
  	<%= f.label :description %><br />
  	<%= f.text_area :description %>
  </p>

  <% number = 0 %>

  <div id="files">
    <%= render partial: "files/form", locals: { number: number } %>
  </div>
  <%= link_to "Add another file", 'javascript:', id: 'add_another_file' %>
  <%= f.submit %>

<% end -%>

app/views/tickets/edit.html.erb
<h4>Editing a ticket in <%= @project.name %></h4>
<%= render "form" %>

app/views/tickets/new.html.erb
<h2>New Ticket</h2>

<%= render 'form' %>

app/views/tickets/show.html.erb
<small>Created by <%= @ticket.user.email %></small>

<h2><%= @ticket.title %></h2>
<%= simple_format(@ticket.description) %>
<% if @ticket.assets.present? %>
  <h3>Attached File</h3>
  <div class="asset">
    <% @ticket.assets.each do |asset| %>
      <p>
        <%= link_to File.basename(asset.asset.path), file_path(asset) %>
      </p>
      <p><small><%= number_to_human_size(asset.asset.size) %></small></p>
    <% end %>
  </div>
<% end %>
<% authorized?("edit tickets", @project) do %>
  <%= link_to "Delete Ticket ", [@project, @ticket], method: :delete %>
  <%= link_to "Edit Ticket", edit_project_ticket_path(@project, @ticket) %>
<% end %>
<h4>Comments:</h4>
<div>
  <% if @ticket.comments.exists? %>
    <%= render @ticket.comments.select(&:persisted?) %>
  <% else %>
    There are no comments for this ticket.
  <% end %>
</div>
<div>
  <%= render "comments/form" %>
</div>