config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    root "base#index"
    resources :users do 
      resources :permissions

      put "permissions", to: "permissions#set", as: "set_permissions"
    end
  end

  root 'projects#index'

  resources :projects do
    resources :tickets
  end

  resources :tickets do
    resources :comments
  end

  resources :users
  resources :files

  get '/signin', to: "sessions#new"
  post '/signin', to: "sessions#create"
  delete '/signout', to: "sessions#destroy", as: "signout"

end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :tickets, dependent: :delete_all
  has_many :permissions, as: :thing
  validates :name, :description, presence: true


  scope :viewable_by, ->(user) do 
    joins(:permissions).where(permissions: { action: "view", user_id: user.id })
  end


  scope :for, ->(user) do
    user.admin? ? Project.all : Project.viewable_by(user)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authorize_admin!, except: [:index, :show]
  before_action :require_signin!, only: [:show, :index]
  before_action :find_project, only: [:show, :update, :edit, :destroy]

  def index	
    @projects = Project.for(current_user)
  end

  def show
  end

  def new
    @project = Project.new
  end

  def edit
  end

  def create
    @project = Project.new(project_params)

    if @project.save
      redirect_to @project, notice: "Project has been created."
    else
      flash[:notice] = "Project has not been created."
      render :new
    end
  end

  def destroy
    @project.destroy

    flash[:notice] = "Project has been deleted."
    redirect_to projects_path
  end

  def update
    @project.update(project_params)

    flash[:notice] = "Project has been updated."
    redirect_to @project
  end

  private

  def find_project
    @project = Project.for(current_user).find(params[:id])
  rescue ActiveRecord::RecordNotFound
    flash[:notice] = "The project you were looking" +
      " for could not be found."
    redirect_to projects_path
  end

  def project_params
    params.require(:project).permit(:name, :description)
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_for @project do |f| %>
  <% if @project.errors.any? %>
    <div id="error">
      <h4><%= pluralize(@project.errors.count, "error") %>
        prohibited this project from being saved:</h4>
      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <p>
  	<%= f.label :name %><br />
  	<%= f.text_field :name %>
  </p>


  <p>
  	<%= f.label :description %><br />
  	<%= f.text_field :description %>
  </p>
  <%= f.submit %>

<% end -%>

app/views/projects/edit.html.erb
<h2>Edit: <%= @project.name %></h2>

<%= render 'form' %>

app/views/projects/index.html.erb
<% admins_only  do %>
  <%= link_to "New Project", new_project_path %>
<% end %>
<h2>Projects</h2>
<ul>

  <% @projects.each do |project| %>
    <li><%= link_to project.name, project %></li>
  <% end %>

</ul>

app/views/projects/new.html.erb
<h2>New Project</h2>

<%= render "form" %>

app/views/projects/show.html.erb
<% content_for :title, title(@project.name) %>
<h2><%= @project.name %></h2>
<% admins_only do %>
  <%= link_to "Edit Project", edit_project_path(@project) %>
  <%= link_to "Delete Project", project_path(@project), method: :delete,
    data: { confirm: "Are you sure you want to delete this project?" }%>
<% end %>
<% authorized?(:"create tickets", @project) do %>
  <%= link_to "New Ticket", new_project_ticket_path(@project) %>
<% end %>
<ul id='tickets'>
  <% @project.tickets.each do |ticket| %>
    <li>
      # <%= ticket.id %> -
      <%= link_to ticket.title, [@project, ticket] %>
    </li>
  <% end %>
</ul>>